# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ephen‘s Blog
subtitle: 奇葩一朵， IT 废材
description:
author: Ephen
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ephen.me
root: /
permalink: :year/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: 
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
  博客折腾: MyBlog
  当时就被震惊: shocking
  工具介绍: tools
  工作笔记: MyWork
  心情驿站: emo
  知识探索: knowledge
tag_map:
  安全: sec
  版权: copyright
  测试: testing
  程序员: coder
  设计师: designer
  网站: website
  虚拟机: vm
  记录类型: rr-type
  产品管理: product-management
  项目管理: project-management
  产品运营: product-operation
  负载均衡器: lb
  备案: beian
  顶级域: root-zone
  泛域名: generic-domain
  解析流程: parsing-process
  域名: domain
  域名格式: zone-format
  协议: protocol
  域转移: zone-transfer
  用户鉴权: user-auth
  域名攻击: attack
  域名劫持: hijacking
  资源协作: co-work


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
plugins:
#- hexo-generator-feed
#- hexo-generator-sitemap

#sitemap
sitemap:
	path: sitemap.xml

#search
search:
  path: search.xml
  field: post

theme: ephen

#disqus
disqus_shortname: ephen

# Security
encrypt:
    enable: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
	type: git
	repo:
		github: https://github.com/ephen/ephen.github.io.git
#		coding: https://git.coding.net/ephen/ephen.git
	branch: master