# >>> Basic Setup | 基础设置 <<<

excerpt_link: more
fancybox: true
mathjax: true
google_analytics: ''

## 是否开启动画效果
animate: true

## 是否在新窗口打开链接
open_in_new: false

# Table of contents | 文章目录
toc:
  on: true
  list_number: true # 目录序号
  max_depth: 3  # 1 - 6 (h1-h6) 目录最大级数
  nowrap: false # Keep title on same line | 目录标题不换行


# >>> Content Setup | 填充内容 <<<

## Small icon of Your site | 站点小图标地址
favicon: /favicon.ico

## Link to your avatar | 博客头像
avatar: /img/avatar.jpg

## Blog Owner | 博客作者信息
author: Ephen
subtitle: 奇葩一朵， IT 废材

## Header | 主菜单
menu:
  主页: /
  所有文章: /archives/
  心情驿站: /categories/emo/
  关于: /About/

## 是否开启标签云
tagcloud: true

## 是否开启友情链接
### friends: false	# 不开启
friends:
  Jerry Qu: https://imququ.com/
  Free技术: https://www.freejishu.com/
  LWL: https://blog.lwl12.com/
  Showfom: https://u.sb
  漠然: https://mritd.me/
  kn007: https://kn007.net/
  DIYgod: https://diygod.me/
  小李子: https://www.lijian.me/
  苏卡卡: https://blog.skk.moe/
  四个空格: https://www.4spaces.org
  极光星空: https://blog.ilemonrain.com
  漩涡: https://xuanwo.io/
  涛叔: https://taoshu.in/

## 是否开启“关于我”。
### aboutme: false	# 不开启
aboutme: <a target='_blank' href='https://www.qingcloud.com/'>QingCloud 青云</a> 产品汪

## Social info. Bar | 社交信息展示
subnav:
  mail: "mailto:ephen@live.cn"
  telegram: "https://telegram.me/imephen"
  twitter: "https://twitter.com/imephen"
  zhihu: "https://www.zhihu.com/people/imephen"
  weibo: "http://weibo.com/cinderellacici"
  rss: /atom.xml
  # google: "#"  
  # github: "https://github.com/ephen"
  # douban: "#"  
  # facebook: "#"  
  # linkedin: "#"

## 是否展示备案号
### beian: false	# 不开启
beian: 鄂 ICP 备 15003996 号

# Local Site Search | 本地站内搜索
## Insatall below plugin to take effect | 使用搜索需先安装对应插件
## https://github.com/PaicHyperionDev/hexo-generator-search
search: 
  on: true
  onload: false
  ## true: get search.xml file when the page has loaded
  ## false: get the file when search box gets focus


## 是否开启分享
share_jia: false
share_addthis: true

## Conments | 评论系统
### duoshuo: ephen.duoshuo.com	# 填写在多说申请的项目名称
### disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: true

# >>> Conments 评论系统 <<<
# Chose ONE as your comment system and keep others disable.
# 选一个作为网站评论系统，其他保持禁用。

disqus: 
  on: true
  shortname: ephen

duoshuo: 
  #on: true
  domain: ephen

youyan:
  #on: true
  id: 2099660
  # 友言服务在 Web 环境下运行，普通本地环境无法查看，请部署后在线上测试。

# Copyright info. of post | 文末版权信息
copyright: true

# >>> CSS/JS CDN <<<
CDN:
  jquery: //cdn.bootcss.com/jquery/2.2.4/jquery.min.js
  require: //cdn.bootcss.com/require.js/2.2.0/require.min.js
  fontawesome: //cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css
  fancybox_js: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.js
  fancybox_css: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
  animate_css: //cdn.bootcss.com/animate.css/3.5.1/animate.min.css
  jquery_ui_js: //cdn.bootcss.com/jqueryui/1.10.4/jquery-ui.min.js
  jquery_ui_css: //cdn.bootcss.com/jqueryui/1.10.4/css/jquery-ui.min.css
  pace_js: //cdn.bootcss.com/pace/1.0.2/pace.min.js
  clipboard: //cdn.bootcss.com/clipboard.js/1.5.10/clipboard.min.js
  mathjax: //cdn.bootcss.com/mathjax/2.6.1/MathJax.js
  scrollreveal: //cdn.bootcss.com/scrollReveal.js/3.1.4/scrollreveal.min.js